export const SPANISH_SYNONYMS = {
  "Alquileres": ["alquiler", "amueblado", "apartamento", "arrendamiento", "arriendo", "campo", "casa", "deposito", "fincas", "garaje"],
  "Servicios": ["agua", "agua caliente", "alarma hogar", "alcantarillado", "antena", "asistente", "caldera", "calefaccion", "canales", "conserje"],
  "Mantenimientos": ["abono", "albanil", "arreglo", "atascos", "averia", "azulejo", "brocha", "cambio bombilla", "carpintero", "cerrajero"],
  "Muebles y deco": ["alfombra", "almohada", "ambientador", "armario", "bodega", "bricolaje decoracion", "butaca", "caja decoracion", "cama", "centro mesa"],
  "Impuestos": ["actos juridicos", "afip", "agencias tributarias", "ahorro", "alcantarillado", "alcohol", "arbitrio", "asesor fiscal", "autoliquidacion", "base imponible"],
  "Combustible": ["95 octanos", "98 octanos", "adblue", "ahorro combustible", "autopista", "barril", "biodiesel", "bomba", "camion cisterna", "carburante"],
  "Transporte publico": ["abono mensual", "abono transporte", "anden", "app taxi", "autobus", "autocar", "ave", "billete", "blablacar", "boleto"],
  "Mantenimiento de vehiculo": ["aceite", "acumulador", "adblue", "aire acondicionado", "alineacion", "amortiguador", "anticongelante", "aparcamiento", "balanceo", "bateria"],
  "Peaje y estacionamiento": ["abono parking", "aparcamiento aeropuerto", "aparcamiento bici", "aparcamiento centro comercial", "aparcamiento cubierto", "aparcamiento descubierto", "aparcamiento disuasorio", "aparcamiento estacion", "aparcamiento moto", "aparcamiento privado"],
  "Seguro de vehiculo": ["accidente", "allianz", "aseguradora vehiculo", "asistencia en carretera", "averia", "axa", "bonus", "choque", "cobertura", "cobertura internacional"],
  "Pago de vehiculos": ["autoescuela", "balloon", "cambio propietario", "carnet", "carta verde", "certificado revision", "clases conduccion", "coche kilometro 0", "coche nuevo", "coche segunda mano"],
  "Otros transportes": ["a caballo", "andar", "avioneta", "barco", "bici", "bici compartida", "bici plegable", "bicibus", "bicicleta", "bicicleta carretera"],
  "Supermercado": ["aceite", "agua mineral", "alimentacion", "alimento mascota", "almacen", "aperitivo", "arroz", "azucar", "bajo calorias", "bebida isotonica"],
  "Restaurantes": ["agua", "almuerzo", "aniversario", "asador", "autoservicio", "bar", "booking", "brunch", "buffet", "cafe"],
  "Cafeterias": ["almuerzo", "americano", "aperitivo", "bar cafe", "batido", "bizcocho", "bocadillo", "bolleria industrial", "brunch", "cafe"],
  "Delivery": ["app comida", "app delivery", "bolsa termica", "codigo promocional", "combo", "comida a casa", "comida a domicilio", "comida china a domicilio", "comida llevar", "comida rapida"],
  "Bebidas": ["absenta", "agua con gas", "agua embotellada", "agua mineral", "agua sabores", "agua sin gas", "agua tonica", "anis", "aperitivo", "barril"],
  "Seguro medico": ["adeslas", "ambulancia", "analitica", "app salud", "aseguradora salud", "asistencia sanitaria", "asistencia telefonica", "asistencia viaje", "baja medica", "capital asegurado"],
  "Medicamentos": ["aerosol", "agua oxigenada", "aguja", "alcohol", "ampolla", "analgesico", "ansiolitico", "antiacido", "antialergico", "antibiotico"],
  "Consultas medicas": ["alergologo", "ambulatorio", "analitica de sangre", "anestesista", "audiologo", "auxiliar de clinica", "baja laboral", "biopsia", "cardiologo", "centro de salud"],
  "Ejercicio": ["abdominales", "acondicionamiento fisico", "actividad fisica", "adelgazar", "aire libre", "aquagym", "artes marciales", "atletismo", "baile", "bandas elasticas"],
  "Higiene": ["acondicionador", "after shave", "alcohol en gel", "algodon", "ambientador", "ambientador bano", "antibacterial", "aseo", "bano", "bastoncillos"],
  "Estetica": ["acido hialuronico", "afeitado tradicional", "antiarrugas", "anticelulitico", "antiedad", "aromaterapia", "aumento de pecho", "automaquillaje", "balayage", "banera de hidromasaje"],
  "Colegiaturas": ["academia", "actividades extraescolares", "ampa", "anillo de graduacion", "anualidad", "asociacion de padres", "autobus escolar", "ayuda educativa", "bachillerato", "beca"],
  "Cursos": ["academia", "academia de idiomas", "acreditacion", "alumno", "aula virtual", "autoescuela", "bonificable", "capacitacion", "carrera", "certificacion"],
  "Materiales": ["acuarelas", "agenda", "alfileres", "archivador", "arcilla", "audiolibro", "barra de pegamento", "bic", "bloc de notas", "block de dibujo"],
  "Suscripciones educativas": ["academia", "acceso ilimitado", "audible", "aula virtual", "autor", "babbel", "badge", "biblioteca digital", "blinkist", "busuu"],
  "Guarderia": ["actividades para ninos", "adaptacion", "almuerzo", "app de comunicacion", "arenero", "au pair", "aula", "autorizacion", "auxiliar de jardin de infancia", "babysitter"],
  "Cine / teatro / eventos": ["3d", "aforo", "anfiteatro", "artista", "auditorio", "baile", "ballet", "banda", "bebida", "benefica"],
  "Streaming": ["alta definicion", "amazon prime", "anime", "apple tv", "atresplayer", "avance", "canal plus", "catalogo", "contenido sin conexion", "continuar viendo"],
  "Videojuegos": ["arma", "artbook", "aspecto", "auriculares gaming", "banda sonora", "battle pass", "battle.net", "blizzard", "caja botin", "call of duty"],
  "Hobbies": ["acampada", "acuario", "aeromodelismo", "aficion", "ajedrez", "analogica", "asociacion", "astronomia", "baile", "bateria"],
  "Viajes y vacaciones": ["accesibilidad", "adaptador enchufe", "aerolinea", "aeropuerto", "airbnb", "all inclusive", "alojamiento", "apartamento turistico", "asistencia en viaje", "autobus"],
  "Deportes": ["abonado", "abono", "album", "apuestas deportivas", "arbitro", "atletismo", "autografo", "balon", "baloncesto", "balonmano"],
  "Regalos": ["accesorios", "adopcion animal", "altavoz", "amigo invisible", "anillo", "aniversario", "arbol", "arte", "articulos de lujo", "auriculares"],
  "Cuidado de niños": ["actividades", "adaptacion del hogar", "apoyo escolar", "au pair", "babyproofing", "babysitter", "bano", "canguro", "carrito", "cena"],
  "Mascotas": ["accesorios mascota", "acogida animal", "acuario", "adiestrador", "adopcion", "alimento humedo", "alimento mascota", "analitica mascota", "antiparasitarios", "arena gato"],
  "Actividades": ["acampada", "actividad familiar", "actividad solidaria", "actuacion", "acuario", "album fotos", "asado", "avistamiento estrellas", "ayuda comunitaria", "barbacoa"],
  "Ropa": ["abrigo", "accesorios", "albornoz", "americana", "armario capsula", "arreglos", "asesoria imagen", "banador", "basicos", "batin"],
  "Calzado": ["adidas", "almohadilla", "alpargata", "ancho", "arreglo calzado", "artesanal", "bailarina", "baile", "ballet", "baloncesto"],
  "Accesorios / joyas": ["accesorio", "alianza", "anillo", "arete", "automatico", "bandolera", "bisuteria", "bolso", "brazalete", "broche"],
  "Comisiones": ["ajd", "american express", "aval", "banca privada", "banca tradicional", "banco", "banco espana", "banco online", "bankia", "bbva"],
  "Intereses / prestamos": ["amortizacion", "amortizacion anticipada", "asnef", "aval", "ayudas", "banco", "bonificacion interes", "caja", "cancelacion hipoteca", "capital"],
  "Ahorros": [",", "acciones", "ahorro", "ahorro automatico", "app ahorro", "apuesta", "ayuda", "banca digital", "beca", "bienes raices"],
  "Inversiones": ["acciones", "adquisicion", "agm", "agresivo", "alfa", "altcoin", "amnistia fiscal", "analisis", "anual", "apalancamiento"],
  "Telefono movil": ["3g", "4g", "5g", "accesibilidad", "accesorios movil", "actualizacion", "adaptador", "almacenamiento", "android", "antena"],
  "Dispositivos": ["2k", "4k", "5ghz", "6e", "8k", "accesorios", "actualizacion", "actualizacion software", "adaptador", "ai"],
  "Apps": ["3ds max", "adobe creative cloud", "after effects", "airbnb", "almacenamiento nube", "amazon appstore", "aplicacion", "app", "app store", "autocad"],
  "Donaciones": ["accion contra hambre", "accion social", "acogida", "agua potable", "albergue", "aldeas infantiles", "alfabetizacion", "alimentos", "alzheimer", "amnesty international"],
  "Ayuda familiar": [",", "accesibilidad", "accidente", "actividades extraescolares", "adaptacion vivienda", "alimentos", "apoyo ancianos", "apoyo discapacitados", "apoyo economico", "apoyo padres"],
  "Otros no clasificados": ["abandono", "absoluto", "acabado", "academico", "accesorios varios", "accidental", "actitudes varias", "activo", "activos circulantes varios", "activos diversos"],
  "Gastos imprevistos": ["abogado urgente", "accidente", "accidente domestico", "accidente trafico", "acto vandalico", "airbnb cancelado", "aire acondicionado roto", "alojamiento emergencia", "ambulancia", "asesoria juridica"],
};